-d D:\Gowin\FPGA_study\fpga_decoder\impl\gwsynthesis\fpga_decoder.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\Gowin\FPGA_study\fpga_decoder\src\fpga_decoder.cst
-cfg D:\Gowin\FPGA_study\fpga_decoder\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
